server:
  port: 8085
spring:
  security:
    user:
      name: vlmuser
      password: vlmuser
      roles: ADMIN, USER

security:
  oauth2:
    client:
      client-id: vlmobile
      client-secret: vlmobile
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token, authorization_code, password, client_credentials
      scope: READ, WRITE, READ_WRITE
    authorization:
      check-token-access: permitAll

